connect 'jdbc:derby:derby/testdb;user=sa;password=password;create=true';
DROP TABLE CODES;
CREATE TABLE CODES (
    CODE VARCHAR(255) NOT NULL,
    PRIMARY KEY (CODE)
);
DROP TABLE PRICE;
CREATE TABLE PRICE (
    CODE VARCHAR(255) NOT NULL,
    DATE TIMESTAMP NOT NULL,
    "OPEN" DECIMAL(8,3),
    HIGH DECIMAL(8,3),
    LOW DECIMAL(8,3),
    "CLOSE" DECIMAL(8,3),
    VOLUME INTEGER,
    PRIMARY KEY (CODE, DATE)
);
DROP TABLE VALUATION;
CREATE TABLE VALUATION (
    CODE VARCHAR(255) NOT NULL,
    DATE TIMESTAMP NOT NULL,
    RATING INTEGER,
    BUY INTEGER,
    HOLD INTEGER,
    SELL INTEGER,
    TARGET DECIMAL(8,3),
    PRIMARY KEY (CODE, DATE)
);
DROP TABLE INDX;
CREATE TABLE INDX (
    IDX VARCHAR(255) NOT NULL,
    DATE TIMESTAMP NOT NULL,
    CODE VARCHAR(255) NOT NULL,
    PRIMARY KEY (IDX,DATE,CODE)
);
DROP TABLE TRADE;
CREATE TABLE TRADE (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    CONFIRMATION_NO VARCHAR(255) NOT NULL,
    DATE TIMESTAMP NOT NULL,
    CODE VARCHAR(255) NOT NULL,
    SIZE INTEGER,
    PRICE DECIMAL(8,3),
    COST DECIMAL(8,2),
    SIDE INTEGER,
    NOTES LONG VARCHAR,
    THEME INTEGER,
    PRIMARY KEY(ID),
    UNIQUE (CONFIRMATION_NO)
    -- FOREIGN KEY (CODE) REFERENCES CODES(CODE)
);
DROP TABLE RANKING;
CREATE TABLE RANKING (
    ID INTEGER NOT NULL,
    DATE TIMESTAMP NOT NULL,
    CODE VARCHAR(255) NOT NULL,
    RANK INTEGER,
    PRIMARY KEY (ID,DATE,CODE)
);
DROP TABLE PAYMENT;
CREATE TABLE PAYMENT (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    TYPE INTEGER NOT NULL,
    DATE TIMESTAMP NOT NULL,
    DETAIL VARCHAR(255) NOT NULL,
    VALUE DECIMAL(8,2) NOT NULL,
    BALANCE DECIMAL(12,2) NOT NULL,
    SIDE INTEGER,
    CODE VARCHAR(255),
    CONTRACTNO VARCHAR(255),
    PRIMARY KEY (ID),
    FOREIGN KEY (CODE) REFERENCES CODES(CODE)
);
DROP TABLE POSITION;
CREATE TABLE POSITION (
    DATE TIMESTAMP NOT NULL,
    CODE VARCHAR(255) NOT NULL,
    SIZE INTEGER,
    COST DECIMAL(12,3),
    COMMISSION DECIMAL(12,3),
    PRIMARY KEY(DATE,CODE)
);


