DROP TABLE CODES IF EXISTS;
CREATE TABLE IF NOT EXISTS CODES (
    CODE VARCHAR(255) NOT NULL,
    PRIMARY KEY (CODE)
);
DROP TABLE PRICE IF EXISTS
CREATE TABLE IF NOT EXISTS PRICE (
    CODE VARCHAR(255) NOT NULL,
    DATE DATETIME NOT NULL,
    OPEN DECIMAL(8,3),
    HIGH DECIMAL(8,3),
    LOW DECIMAL(8,3),
    CLOSE DECIMAL(8,3),
    VOLUME INTEGER,
    PRIMARY KEY (CODE, DATE)
);
DROP TABLE VALUATION IF EXISTS
CREATE TABLE IF NOT EXISTS VALUATION (
    CODE VARCHAR(255) NOT NULL,
    DATE DATETIME NOT NULL,
    RATING INTEGER,
    BUY INTEGER,
    HOLD INTEGER,
    SELL INTEGER,
    TARGET DECIMAL(8,3),
    PRIMARY KEY (CODE, DATE)
);
DROP TABLE INDX IF EXISTS
CREATE TABLE IF NOT EXISTS INDX (
    IDX VARCHAR(255) NOT NULL,
    DATE DATETIME NOT NULL,
    CODE VARCHAR(255) NOT NULL,
    PRIMARY KEY (IDX,DATE,CODE)
);
DROP TABLE TRADE IF EXISTS
CREATE TABLE IF NOT EXISTS TRADE (
    ID INTEGER NOT NULL IDENTITY,
    CONFIRMATION_NO VARCHAR(255) NOT NULL,
    DATE DATETIME NOT NULL,
    CODE VARCHAR(255) NOT NULL,
    SIZE INTEGER,
    PRICE DECIMAL(8,3),
    COST DECIMAL(8,2),
    SIDE INTEGER,
    NOTES VARCHAR(100000),
    PRIMARY KEY(ID),
    UNIQUE (CONFIRMATION_NO)
    -- FOREIGN KEY (CODE) REFERENCES CODES(CODE)
);
DROP TABLE RANKING IF EXISTS
CREATE TABLE IF NOT EXISTS RANKING (
    ID INTEGER NOT NULL,
    DATE DATETIME NOT NULL,
    CODE VARCHAR(255) NOT NULL,
    RANK INTEGER,
    PRIMARY KEY (ID,DATE,CODE)
);
DROP TABLE PAYMENT IF EXISTS
CREATE TABLE IF NOT EXISTS PAYMENT (
    ID INTEGER NOT NULL IDENTITY,
    TYPE INTEGER NOT NULL,
    DATE DATETIME NOT NULL,
    DETAIL VARCHAR(255) NOT NULL,
    VALUE DECIMAL(8,2) NOT NULL,
    BALANCE DECIMAL(12,2) NOT NULL,
    SIDE INTEGER,
    CODE VARCHAR(255),
    CONTRACTNO VARCHAR(255),
    PRIMARY KEY (ID),
    FOREIGN KEY (CODE) REFERENCES CODES(CODE)
);
DROP TABLE POSITION IF EXISTS;
CREATE TABLE IF NOT EXISTS POSITION (
    DATE DATETIME NOT NULL,
    CODE VARCHAR(255) NOT NULL,
    SIZE INTEGER,
    COST DECIMAL(12,3),
    PRIMARY KEY(DATE,CODE)
);


