DROP TABLE price;
CREATE TABLE IF NOT EXISTS price (
    _CODE VARCHAR(255) NOT NULL,
    _DATE DATETIME NOT NULL,
    _OPEN DECIMAL(8,3),
    _HIGH DECIMAL(8,3),
    _LOW DECIMAL(8,3),
    _CLOSE DECIMAL(8,3),
    _VOLUME INTEGER,
    PRIMARY KEY (_CODE, _DATE)
);
DROP TABLE VALUATION;
CREATE TABLE IF NOT EXISTS VALUATION (
    CODE VARCHAR(255) NOT NULL,
    _DATE DATETIME NOT NULL,
    RATING INTEGER,
    BUY INTEGER,
    HOLD INTEGER,
    SELL INTEGER,
    TARGET DECIMAL(8,3),
    PRIMARY KEY (CODE, _DATE)
);
DROP TABLE FUNDAMENTALLY_SOUND;
CREATE TABLE IF NOT EXISTS FUNDAMENTALLY_SOUND (
    _DATE DATETIME NOT NULL,
    CODE VARCHAR(255) NOT NULL,
    PRIMARY KEY (_DATE,CODE)
);
DROP TABLE INDX;
CREATE TABLE IF NOT EXISTS INDX (
    IDX VARCHAR(255) NOT NULL,
    _DATE DATETIME NOT NULL,
    CODE VARCHAR(255) NOT NULL,
    PRIMARY KEY (IDX,_DATE,CODE)
);
DROP TABLE TRADE;
CREATE TABLE IF NOT EXISTS TRADE (
    ID INT NOT NULL AUTO_INCREMENT,
    CONFIRMATION_NO VARCHAR(255) NOT NULL,
    _DATE DATETIME NOT NULL,
    CODE VARCHAR(255) NOT NULL,
    SIZE INTEGER,
    PRICE DECIMAL(8,3),
    COST DECIMAL(8,2),
    SIDE INTEGER,
    NOTES VARCHAR(255),
    PRIMARY KEY(ID),
    UNIQUE (CONFIRMATION_NO)
);


