DROP TABLE price;
CREATE TABLE IF NOT EXISTS price (
    _CODE VARCHAR(255) NOT NULL,
    _DATE DATETIME NOT NULL,
    _OPEN DECIMAL(8,3),
    _HIGH DECIMAL(8,3),
    _LOW DECIMAL(8,3),
    _CLOSE DECIMAL(8,3),
    _VOLUME INTEGER,
    PRIMARY KEY (_CODE, _DATE)
);
DROP TABLE VALUATION;
CREATE TABLE IF NOT EXISTS VALUATION (
    CODE VARCHAR(255) NOT NULL,
    _DATE DATETIME NOT NULL,
    RATING INTEGER,
    BUY INTEGER,
    HOLD INTEGER,
    SELL INTEGER,
    TARGET DECIMAL(8,3),
    PRIMARY KEY (CODE, _DATE)
);


